---
- hosts: targetservers

  tasks:
   - name: Check a command
     command: date

   - name: install httpd through yum
     yum:
       name: httpd
       state: present

   - name: ping targetserver
     ping:

   - name: start the httpd service
     service:
        name: httpd
        state: started
